version: "3.8"
#
# Services definitions
#
services:
    app:
        image: kooldev/php:8.2-nginx
        ports:
            - "${KOOL_APP_PORT:-8000}:80"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global

    horizon:
        image: kooldev/php:8.2-nginx
        command: php artisan horizon
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global
        restart: on-failure

    database:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "${KOOL_DATABASE_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-rootpass}"
            MYSQL_DATABASE: "${DB_DATABASE-database}"
            MYSQL_USER: "${DB_USERNAME-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD-pass}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - database:/var/lib/mysql:delegated
        networks:
            - kool_local
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]

    cache:
        image: redis:7-alpine
        volumes:
            - cache:/data:delegated
        networks:
            - kool_local
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID:-ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY:-APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET:-APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - kool_local
#
# Networks definitions
#
networks:
    kool_local:
    kool_global:
        external: true
        name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
    database:
    cache:
    memcached:
    rabbitmq:
