version: "3.8"
#
# Services definitions
#
services:
    dev:
        image: kooldev/php:8.2-swoole
        command: php artisan serve --host=0.0.0.0 --port=80
        ports:
            - "${KOOL_APP_PORT_DEV:-8000}:80"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global

    app:
        image: kooldev/php:8.2-swoole
        command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=80 --watch --poll
        ports:
            - "${KOOL_APP_PORT:-8001}:80"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global
    register-click-command:
        image: kooldev/php:8.2-swoole
        command: php artisan app:register-click-command
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global
        restart: on-failure
    database:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "${KOOL_DATABASE_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-rootpass}"
            MYSQL_DATABASE: "${DB_DATABASE-database}"
            MYSQL_USER: "${DB_USERNAME-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD-pass}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - database:/var/lib/mysql:delegated
        networks:
            - kool_local
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
    cache:
        image: redis:7-alpine
        volumes:
            - cache:/data:delegated
        networks:
            - kool_local
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

    memcached:
        image: memcached:1.6-alpine
        volumes:
            - memcached:/data:delegated
        networks:
            - kool_local

    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "5672:5672"  # Porta padrão para conexões AMQP
            - "15672:15672" # Porta para o painel de controle da RabbitMQ (opcional, acesso via http://localhost:15672)
        environment:
            #RABBITMQ_ERLANG_COOKIE: "cookie-secreto-aqui" # Substitua por um valor seguro para o Erlang cookie
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - kool_local
            - kool_global
#
# Networks definitions
#
networks:
    kool_local:
    kool_global:
        external: true
        name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
    database:
    cache:
    memcached:
    rabbitmq:
