<?php

namespace Tests;

use App\Shared\RabbitMQ;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Tests\Feature\Stub\RabbitMQStub;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app->singleton(RabbitMQ::class, RabbitMQStub::class);
    }
}
